const seedData = {
  metrics: {
    ordersToday: 18,
    revenueToday: 4286.7,
    lowStock: 5,
    reservationsToday: 7,
  },

  recentOrders: [
    {
      id: "PED-1048",
      customer: "Mariana Costa",
      total: 189.8,
      status: "Separação",
      channel: "E-commerce",
      time: "16:42",
    },
    {
      id: "PED-1047",
      customer: "Lucas Almeida",
      total: 249.9,
      status: "Pago",
      channel: "Quiosque SP 01",
      time: "16:18",
    },
    {
      id: "PED-1046",
      customer: "Carla Mendes",
      total: 134.7,
      status: "Enviado",
      channel: "E-commerce",
      time: "15:51",
    },
    {
      id: "PED-1045",
      customer: "Rafael Lima",
      total: 329.4,
      status: "Recebido",
      channel: "E-commerce",
      time: "15:23",
    },
    {
      id: "PED-1044",
      customer: "Fernanda Rocha",
      total: 97.9,
      status: "Entregue",
      channel: "Quiosque Belém 01",
      time: "14:57",
    },
  ],
  orders: [
    {
      id: "PED-1048",
      customer: "Mariana Costa",
      email: "mariana@email.com",
      channel: "E-commerce",
      date: "24/09/2026",
      time: "16:42",
      status: "Separação",
      payment: "PIX",
      total: 189.8,
      items: 3,
    },
    {
      id: "PED-1047",
      customer: "Lucas Almeida",
      email: "lucas@email.com",
      channel: "Quiosque SP 01",
      date: "24/09/2026",
      time: "16:18",
      status: "Pago",
      payment: "Cartão",
      total: 249.9,
      items: 4,
    },
    {
      id: "PED-1046",
      customer: "Carla Mendes",
      email: "carla@email.com",
      channel: "E-commerce",
      date: "24/09/2026",
      time: "15:51",
      status: "Enviado",
      payment: "Cartão",
      total: 134.7,
      items: 2,
    },
    {
      id: "PED-1045",
      customer: "Rafael Lima",
      email: "rafael@email.com",
      channel: "E-commerce",
      date: "24/09/2026",
      time: "15:23",
      status: "Recebido",
      payment: "PIX",
      total: 329.4,
      items: 5,
    },
    {
      id: "PED-1044",
      customer: "Fernanda Rocha",
      email: "fernanda@email.com",
      channel: "Quiosque Belém 01",
      date: "24/09/2026",
      time: "14:57",
      status: "Entregue",
      payment: "Cartão",
      total: 97.9,
      items: 1,
    },
    {
      id: "PED-1043",
      customer: "Paulo Henrique",
      email: "paulo@email.com",
      channel: "E-commerce",
      date: "23/09/2026",
      time: "21:15",
      status: "Entregue",
      payment: "PIX",
      total: 214.6,
      items: 3,
    },
    {
      id: "PED-1042",
      customer: "Ana Beatriz",
      email: "ana@email.com",
      channel: "Quiosque Brasília 01",
      date: "23/09/2026",
      time: "19:47",
      status: "Cancelado",
      payment: "Cartão",
      total: 149.9,
      items: 2,
    },
    {
      id: "PED-1041",
      customer: "Gabriel Souza",
      email: "gabriel@email.com",
      channel: "E-commerce",
      date: "23/09/2026",
      time: "18:12",
      status: "Separação",
      payment: "Cartão",
      total: 287.5,
      items: 4,
    },
  ],

  lowStockProducts: [
    {
      name: "Lumina Brut",
      stock: 4,
      minimum: 10,
    },
    {
      name: "Casa Serena Rosé",
      stock: 6,
      minimum: 12,
    },
    {
      name: "Noite Alta Malbec",
      stock: 7,
      minimum: 12,
    },
    {
      name: "Terra Alta Branco",
      stock: 8,
      minimum: 10,
    },
    {
      name: "Serra Clara Moscatel",
      stock: 9,
      minimum: 12,
    },
  ],

  upcomingReservations: [
    {
      id: "RES-203",
      experience: "Degustação Guiada",
      customer: "Amanda Ferreira",
      people: 4,
      date: "Hoje",
      time: "19:00",
      status: "Confirmada",
    },
    {
      id: "RES-204",
      experience: "Descoberta de Tintos",
      customer: "Eduardo Silva",
      people: 2,
      date: "Hoje",
      time: "20:30",
      status: "Confirmada",
    },
    {
      id: "RES-205",
      experience: "Vinhos & Harmonização",
      customer: "Juliana Martins",
      people: 6,
      date: "Amanhã",
      time: "18:30",
      status: "Pendente",
    },
  ],

  products: [
    {
      id: "P001",
      name: "Serra Velha Cabernet Sauvignon",
      category: "Tinto",
      line: "Repertório",
      price: 74.9,
      cost: 46.5,
      stock: 42,
      minimum: 15,
    },
    {
      id: "P002",
      name: "Noite Alta Malbec",
      category: "Tinto",
      line: "Repertório",
      price: 79.9,
      cost: 43.8,
      stock: 18,
      minimum: 12,
    },
    {
      id: "P003",
      name: "Casa Serena Rosé",
      category: "Rosé",
      line: "Descoberta",
      price: 64.9,
      cost: 34.2,
      stock: 6,
      minimum: 12,
    },
    {
      id: "P004",
      name: "Terra Alta Branco",
      category: "Branco",
      line: "Descoberta",
      price: 72.9,
      cost: 38.4,
      stock: 8,
      minimum: 10,
    },
    {
      id: "P005",
      name: "Lumina Brut",
      category: "Espumante",
      line: "Repertório",
      price: 89.9,
      cost: 49.9,
      stock: 4,
      minimum: 10,
    },
    {
      id: "P006",
      name: "Serra Clara Moscatel",
      category: "Espumante",
      line: "Descoberta",
      price: 69.9,
      cost: 36.9,
      stock: 9,
      minimum: 12,
    },
    {
      id: "P007",
      name: "Vale Claro Chenin Blanc",
      category: "Branco",
      line: "Repertório",
      price: 84.9,
      cost: 44.5,
      stock: 31,
      minimum: 10,
    },
    {
      id: "P008",
      name: "Cerro Negro Bonarda",
      category: "Tinto",
      line: "Repertório",
      price: 82.9,
      cost: 42.5,
      stock: 27,
      minimum: 12,
    },
    {
      id: "P009",
      name: "Aurora Rosé",
      category: "Rosé",
      line: "Descoberta",
      price: 67.9,
      cost: 35.2,
      stock: 16,
      minimum: 10,
    },
    {
      id: "P010",
      name: "Costa Clara Rosé",
      category: "Rosé",
      line: "Repertório",
      price: 76.9,
      cost: 39.9,
      stock: 24,
      minimum: 10,
    },
    {
      id: "P011",
      name: "Monte Claro Brut",
      category: "Espumante",
      line: "Seleção",
      price: 109.9,
      cost: 62.5,
      stock: 14,
      minimum: 8,
    },
    {
      id: "P012",
      name: "Vale del Sol Tinto",
      category: "Tinto",
      line: "Descoberta",
      price: 58.9,
      cost: 31.2,
      stock: 38,
      minimum: 15,
    },
],
customers: [
  {
    id: "CLI-001",
    name: "Mariana Costa",
    email: "mariana@email.com",
    phone: "(11) 99814-2201",
    profile: "Repertório",
    origin: "Instagram",
    city: "São Paulo",
    state: "SP",
    joinedAt: "12/04/2026",
  },
  {
    id: "CLI-002",
    name: "Lucas Almeida",
    email: "lucas@email.com",
    phone: "(11) 99122-7304",
    profile: "Entusiasta",
    origin: "Quiosque",
    city: "São Paulo",
    state: "SP",
    joinedAt: "28/03/2026",
  },
  {
    id: "CLI-003",
    name: "Carla Mendes",
    email: "carla@email.com",
    phone: "(21) 99718-0144",
    profile: "Descoberta",
    origin: "Google",
    city: "Rio de Janeiro",
    state: "RJ",
    joinedAt: "09/06/2026",
  },
  {
    id: "CLI-004",
    name: "Rafael Lima",
    email: "rafael@email.com",
    phone: "(61) 99670-1880",
    profile: "Repertório",
    origin: "Wine Finder",
    city: "Brasília",
    state: "DF",
    joinedAt: "18/05/2026",
  },
  {
    id: "CLI-005",
    name: "Fernanda Rocha",
    email: "fernanda@email.com",
    phone: "(91) 98466-9201",
    profile: "Descoberta",
    origin: "Quiosque",
    city: "Belém",
    state: "PA",
    joinedAt: "21/07/2026",
  },
  {
    id: "CLI-006",
    name: "Paulo Henrique",
    email: "paulo@email.com",
    phone: "(31) 99481-5560",
    profile: "Entusiasta",
    origin: "Indicação",
    city: "Belo Horizonte",
    state: "MG",
    joinedAt: "15/03/2026",
  },
  {
    id: "CLI-007",
    name: "Ana Beatriz",
    email: "ana@email.com",
    phone: "(61) 99802-3185",
    profile: "Descoberta",
    origin: "Instagram",
    city: "Brasília",
    state: "DF",
    joinedAt: "30/06/2026",
  },
  {
    id: "CLI-008",
    name: "Gabriel Souza",
    email: "gabriel@email.com",
    phone: "(91) 98341-1706",
    profile: "Repertório",
    origin: "Wine Finder",
    city: "Belém",
    state: "PA",
    joinedAt: "04/04/2026",
  },
],
  reservations: [
  {
    id: "RES-203",
    customer: "Amanda Ferreira",
    email: "amanda@email.com",
    experience: "Degustação Guiada",
    date: "25/09/2026",
    time: "19:00",
    people: 4,
    location: "Quiosque Belém 01",
    status: "Confirmada",
    notes: "Preferência por tintos leves.",
  },
  {
    id: "RES-204",
    customer: "Eduardo Silva",
    email: "eduardo@email.com",
    experience: "Descoberta de Tintos",
    date: "25/09/2026",
    time: "20:30",
    people: 2,
    location: "Quiosque SP 01",
    status: "Confirmada",
    notes: "",
  },
  {
    id: "RES-205",
    customer: "Juliana Martins",
    email: "juliana@email.com",
    experience: "Vinhos & Harmonização",
    date: "26/09/2026",
    time: "18:30",
    people: 6,
    location: "Quiosque Brasília 01",
    status: "Pendente",
    notes: "Aniversário em grupo.",
  },
  {
    id: "RES-206",
    customer: "Ricardo Alves",
    email: "ricardo@email.com",
    experience: "Primeiros Passos no Vinho",
    date: "26/09/2026",
    time: "20:00",
    people: 3,
    location: "Quiosque Belém 02",
    status: "Pendente",
    notes: "",
  },
  {
    id: "RES-207",
    customer: "Camila Nunes",
    email: "camila@email.com",
    experience: "Degustação Guiada",
    date: "27/09/2026",
    time: "17:00",
    people: 2,
    location: "Quiosque SP 02",
    status: "Confirmada",
    notes: "Primeira experiência com vinhos.",
  },
  {
    id: "RES-208",
    customer: "Bruno Carvalho",
    email: "bruno@email.com",
    experience: "Espumantes sem Mistério",
    date: "27/09/2026",
    time: "19:30",
    people: 4,
    location: "Quiosque Rio 01",
    status: "Cancelada",
    notes: "",
  },
],

};
  

export default seedData;