const seedData = {
  metrics: {
    ordersToday: 18,
    revenueToday: 4286.7,
    lowStock: 5,
    reservationsToday: 7,
  },

  recentOrders: [
    {
      id: "PED-1048",
      customer: "Mariana Costa",
      total: 189.8,
      status: "Separação",
      channel: "E-commerce",
      time: "16:42",
    },
    {
      id: "PED-1047",
      customer: "Lucas Almeida",
      total: 249.9,
      status: "Pago",
      channel: "Quiosque SP 01",
      time: "16:18",
    },
    {
      id: "PED-1046",
      customer: "Carla Mendes",
      total: 134.7,
      status: "Enviado",
      channel: "E-commerce",
      time: "15:51",
    },
    {
      id: "PED-1045",
      customer: "Rafael Lima",
      total: 329.4,
      status: "Recebido",
      channel: "E-commerce",
      time: "15:23",
    },
    {
      id: "PED-1044",
      customer: "Fernanda Rocha",
      total: 97.9,
      status: "Entregue",
      channel: "Quiosque Belém 01",
      time: "14:57",
    },
  ],
  orders: [
    {
      id: "PED-1048",
      customer: "Mariana Costa",
      email: "mariana@email.com",
      channel: "E-commerce",
      date: "24/09/2026",
      time: "16:42",
      status: "Separação",
      payment: "PIX",
      total: 189.8,
      items: 3,
    },
    {
      id: "PED-1047",
      customer: "Lucas Almeida",
      email: "lucas@email.com",
      channel: "Quiosque SP 01",
      date: "24/09/2026",
      time: "16:18",
      status: "Pago",
      payment: "Cartão",
      total: 249.9,
      items: 4,
    },
    {
      id: "PED-1046",
      customer: "Carla Mendes",
      email: "carla@email.com",
      channel: "E-commerce",
      date: "24/09/2026",
      time: "15:51",
      status: "Enviado",
      payment: "Cartão",
      total: 134.7,
      items: 2,
    },
    {
      id: "PED-1045",
      customer: "Rafael Lima",
      email: "rafael@email.com",
      channel: "E-commerce",
      date: "24/09/2026",
      time: "15:23",
      status: "Recebido",
      payment: "PIX",
      total: 329.4,
      items: 5,
    },
    {
      id: "PED-1044",
      customer: "Fernanda Rocha",
      email: "fernanda@email.com",
      channel: "Quiosque Belém 01",
      date: "24/09/2026",
      time: "14:57",
      status: "Entregue",
      payment: "Cartão",
      total: 97.9,
      items: 1,
    },
    {
      id: "PED-1043",
      customer: "Paulo Henrique",
      email: "paulo@email.com",
      channel: "E-commerce",
      date: "23/09/2026",
      time: "21:15",
      status: "Entregue",
      payment: "PIX",
      total: 214.6,
      items: 3,
    },
    {
      id: "PED-1042",
      customer: "Ana Beatriz",
      email: "ana@email.com",
      channel: "Quiosque Brasília 01",
      date: "23/09/2026",
      time: "19:47",
      status: "Cancelado",
      payment: "Cartão",
      total: 149.9,
      items: 2,
    },
    {
      id: "PED-1041",
      customer: "Gabriel Souza",
      email: "gabriel@email.com",
      channel: "E-commerce",
      date: "23/09/2026",
      time: "18:12",
      status: "Separação",
      payment: "Cartão",
      total: 287.5,
      items: 4,
    },
  ],

  lowStockProducts: [
    {
      name: "Lumina Brut",
      stock: 4,
      minimum: 10,
    },
    {
      name: "Casa Serena Rosé",
      stock: 6,
      minimum: 12,
    },
    {
      name: "Noite Alta Malbec",
      stock: 7,
      minimum: 12,
    },
    {
      name: "Terra Alta Branco",
      stock: 8,
      minimum: 10,
    },
    {
      name: "Serra Clara Moscatel",
      stock: 9,
      minimum: 12,
    },
  ],

  upcomingReservations: [
    {
      id: "RES-203",
      experience: "Degustação Guiada",
      customer: "Amanda Ferreira",
      people: 4,
      date: "Hoje",
      time: "19:00",
      status: "Confirmada",
    },
    {
      id: "RES-204",
      experience: "Descoberta de Tintos",
      customer: "Eduardo Silva",
      people: 2,
      date: "Hoje",
      time: "20:30",
      status: "Confirmada",
    },
    {
      id: "RES-205",
      experience: "Vinhos & Harmonização",
      customer: "Juliana Martins",
      people: 6,
      date: "Amanhã",
      time: "18:30",
      status: "Pendente",
    },
  ],
};

export default seedData;